import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright smoke tests for the i18n migration safety net.
 *
 * Catches MISSING_MESSAGE crashes that get past:
 *  - `tsc --noEmit` (typed messages handle static keys, dynamic keys are cast)
 *  - `scripts/audit-missing-keys-v3.py` (catches static missing keys but not
 *    keys generated by interpolated dynamic patterns at runtime)
 *
 * Tests focus on PUBLIC routes (no DB / auth) across all 3 locales.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [["list"]],
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000",
    trace: "on-first-retry",
    // Suppress Next.js dev overlay so screenshots are clean.
    headless: true,
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
  ],
  // Spawn the dev server automatically. Reuses an already-running one.
  webServer: {
    command: "npm run dev",
    url: "http://localhost:3000",
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: "ignore",
    stderr: "pipe",
  },
});
